const codes = [
    { "ADM0_CODE": 1, ISO2: "AF", name: "Afghanistan" },
    { "ADM0_CODE": 3, ISO2: "AL", name: "Albania" },
    { "ADM0_CODE": 4, ISO2: "DZ", name: "Algeria" },
    { "ADM0_CODE": 5, ISO2: "AS", name: "American Samoa" },
    { "ADM0_CODE": 7, ISO2: "AD", name: "Andorra" },
    { "ADM0_CODE": 8, ISO2: "AO", name: "Angola" },
    { "ADM0_CODE": 9, ISO2: "AI", name: "Anguilla" },
    { "ADM0_CODE": 10, ISO2: "AQ", name: "Antarctica" },
    { "ADM0_CODE": 11, ISO2: "AG", name: "Antigua and Barbuda" },
    { "ADM0_CODE": 12, ISO2: "AR", name: "Argentina" },
    { "ADM0_CODE": 13, ISO2: "AM", name: "Armenia" },
    { "ADM0_CODE": 14, ISO2: "AW", name: "Aruba" },
    { "ADM0_CODE": 17, ISO2: "AU", name: "Australia" },
    { "ADM0_CODE": 18, ISO2: "AT", name: "Austria" },
    { "ADM0_CODE": 19, ISO2: "AZ", name: "Azerbaijan" },
    { "ADM0_CODE": 20, ISO2: "BS", name: "Bahamas" },
    { "ADM0_CODE": 21, ISO2: "BH", name: "Bahrain" },
    { "ADM0_CODE": 23, ISO2: "BD", name: "Bangladesh" },
    { "ADM0_CODE": 24, ISO2: "BB", name: "Barbados" },
    { "ADM0_CODE": 26, ISO2: "BY", name: "Belarus" },
    { "ADM0_CODE": 27, ISO2: "BE", name: "Belgium" },
    { "ADM0_CODE": 28, ISO2: "BZ", name: "Belize" },
    { "ADM0_CODE": 29, ISO2: "BJ", name: "Benin" },
    { "ADM0_CODE": 30, ISO2: "BM", name: "Bermuda" },
    { "ADM0_CODE": 31, ISO2: "BT", name: "Bhutan" },
    { "ADM0_CODE": 33, ISO2: "BO", name: "Bolivia (Plurinational State of)" },
    { "ADM0_CODE": 34, ISO2: "BA", name: "Bosnia and Herzegovina" },
    { "ADM0_CODE": 35, ISO2: "BW", name: "Botswana" },
    { "ADM0_CODE": 36, ISO2: "BV", name: "Bouvet Island" },
    { "ADM0_CODE": 37, ISO2: "BR", name: "Brazil" },
    { "ADM0_CODE": 38, ISO2: "IO", name: "British Indian Ocean Territory" },
    { "ADM0_CODE": 39, ISO2: "VG", name: "Virgin Islands (British)" },
    { "ADM0_CODE": 40, ISO2: "BN", name: "Brunei Darussalam" },
    { "ADM0_CODE": 41, ISO2: "BG", name: "Bulgaria" },
    { "ADM0_CODE": 42, ISO2: "BF", name: "Burkina Faso" },
    { "ADM0_CODE": 43, ISO2: "BI", name: "Burundi" },
    { "ADM0_CODE": 44, ISO2: "KH", name: "Cambodia" },
    { "ADM0_CODE": 45, ISO2: "CM", name: "Cameroon" },
    { "ADM0_CODE": 46, ISO2: "CA", name: "Canada" },
    { "ADM0_CODE": 47, ISO2: "CV", name: "Cabo Verde" },
    { "ADM0_CODE": 48, ISO2: "KY", name: "Cayman Islands" },
    { "ADM0_CODE": 49, ISO2: "CF", name: "Central African Republic" },
    { "ADM0_CODE": 50, ISO2: "TD", name: "Chad" },
    { "ADM0_CODE": 51, ISO2: "CL", name: "Chile" },
    { "ADM0_CODE": 147295, ISO2: "CN", name: "China" },
    { "ADM0_CODE": 54, ISO2: "CX", name: "Christmas Island" },
    { "ADM0_CODE": 56, ISO2: "CC", name: "Cocos (Keeling) Islands" },
    { "ADM0_CODE": 57, ISO2: "CO", name: "Colombia" },
    { "ADM0_CODE": 58, ISO2: "KM", name: "Comoros" },
    { "ADM0_CODE": 59, ISO2: "CG", name: "Congo" },
    { "ADM0_CODE": 60, ISO2: "CK", name: "Cook Islands" },
    { "ADM0_CODE": 61, ISO2: "CR", name: "Costa Rica" },
    { "ADM0_CODE": 66, ISO2: "CI", name: "Côte d'Ivoire" },
    { "ADM0_CODE": 62, ISO2: "HR", name: "Croatia" },
    { "ADM0_CODE": 63, ISO2: "CU", name: "Cuba" },
    { "ADM0_CODE": 64, ISO2: "CY", name: "Cyprus" },
    { "ADM0_CODE": 65, ISO2: "CZ", name: "Czechia" },
    { "ADM0_CODE": 67, ISO2: "KP", name: "Korea (Democratic People's Republic of)" },
    { "ADM0_CODE": 68, ISO2: "CD", name: "Congo, Democratic Republic of the" },
    { "ADM0_CODE": 69, ISO2: "DK", name: "Denmark" },
    { "ADM0_CODE": 70, ISO2: "DJ", name: "Djibouti" },
    { "ADM0_CODE": 71, ISO2: "DM", name: "Dominica" },
    { "ADM0_CODE": 72, ISO2: "DO", name: "Dominican Republic" },
    { "ADM0_CODE": 73, ISO2: "EC", name: "Ecuador" },
    { "ADM0_CODE": 40765, ISO2: "EG", name: "Egypt" },
    { "ADM0_CODE": 75, ISO2: "SV", name: "El Salvador" },
    { "ADM0_CODE": 76, ISO2: "GQ", name: "Equatorial Guinea" },
    { "ADM0_CODE": 77, ISO2: "ER", name: "Eritrea" },
    { "ADM0_CODE": 78, ISO2: "EE", name: "Estonia" },
    { "ADM0_CODE": 79, ISO2: "ET", name: "Ethiopia" },
    { "ADM0_CODE": 81, ISO2: "FK", name: "Falkland Islands (Malvinas)" },
    { "ADM0_CODE": 82, ISO2: "FO", name: "Faroe Islands" },
    { "ADM0_CODE": 83, ISO2: "FJ", name: "Fiji" },
    { "ADM0_CODE": 84, ISO2: "FI", name: "Finland" },
    { "ADM0_CODE": 85, ISO2: "FR", name: "France" },
    { "ADM0_CODE": 86, ISO2: "GF", name: "French Guiana" },
    { "ADM0_CODE": 87, ISO2: "PF", name: "French Polynesia" },
    { "ADM0_CODE": 88, ISO2: "TF", name: "French Southern Territories" },
    { "ADM0_CODE": 89, ISO2: "GA", name: "Gabon" },
    { "ADM0_CODE": 90, ISO2: "GM", name: "Gambia" },
    { "ADM0_CODE": 92, ISO2: "GE", name: "Georgia" },
    { "ADM0_CODE": 93, ISO2: "DE", name: "Germany" },
    { "ADM0_CODE": 94, ISO2: "GH", name: "Ghana" },
    { "ADM0_CODE": 95, ISO2: "GI", name: "Gibraltar" },
    { "ADM0_CODE": 97, ISO2: "GR", name: "Greece" },
    { "ADM0_CODE": 98, ISO2: "GL", name: "Greenland" },
    { "ADM0_CODE": 99, ISO2: "GD", name: "Grenada" },
    { "ADM0_CODE": 100, ISO2: "GP", name: "Guadeloupe" },
    { "ADM0_CODE": 101, ISO2: "GU", name: "Guam" },
    { "ADM0_CODE": 103, ISO2: "GT", name: "Guatemala" },
    { "ADM0_CODE": 104, ISO2: "GG", name: "Guernsey" },
    { "ADM0_CODE": 106, ISO2: "GN", name: "Guinea" },
    { "ADM0_CODE": 105, ISO2: "GW", name: "Guinea-Bissau" },
    { "ADM0_CODE": 107, ISO2: "GY", name: "Guyana" },
    { "ADM0_CODE": 108, ISO2: "HT", name: "Haiti" },
    { "ADM0_CODE": 109, ISO2: "HM", name: "Heard Island and McDonald Islands" },
    { "ADM0_CODE": 110, ISO2: "VA", name: "Holy See" },
    { "ADM0_CODE": 111, ISO2: "HN", name: "Honduras" },
    { "ADM0_CODE": 33364, ISO2: "HK", name: "Hong Kong" },
    { "ADM0_CODE": 113, ISO2: "HU", name: "Hungary" },
    { "ADM0_CODE": 114, ISO2: "IS", name: "Iceland" },
    { "ADM0_CODE": 115, ISO2: "IN", name: "India" },
    { "ADM0_CODE": 116, ISO2: "ID", name: "Indonesia" },
    { "ADM0_CODE": 117, ISO2: "IR", name: "Iran (Islamic Republic of)" },
    { "ADM0_CODE": 118, ISO2: "IQ", name: "Iraq" },
    { "ADM0_CODE": 119, ISO2: "IE", name: "Ireland" },
    { "ADM0_CODE": 120, ISO2: "IM", name: "Isle of Man" },
    { "ADM0_CODE": 121, ISO2: "IL", name: "Israel" },
    { "ADM0_CODE": 122, ISO2: "IT", name: "Italy" },
    { "ADM0_CODE": 123, ISO2: "JM", name: "Jamaica" },
    { "ADM0_CODE": 126, ISO2: "JP", name: "Japan" },
    { "ADM0_CODE": 128, ISO2: "JE", name: "Jersey" },
    { "ADM0_CODE": 130, ISO2: "JO", name: "Jordan" },
    { "ADM0_CODE": 132, ISO2: "KZ", name: "Kazakhstan" },
    { "ADM0_CODE": 133, ISO2: "KE", name: "Kenya" },
    { "ADM0_CODE": 135, ISO2: "KI", name: "Kiribati" },
    { "ADM0_CODE": 136, ISO2: "KW", name: "Kuwait" },
    { "ADM0_CODE": 137, ISO2: "KG", name: "Kyrgyzstan" },
    { "ADM0_CODE": 138, ISO2: "KG", name: "Kyrgyzstan" },
    { "ADM0_CODE": 139, ISO2: "LA", name: "Lao People's Democratic Republic" },
    { "ADM0_CODE": 140, ISO2: "LV", name: "Latvia" },
    { "ADM0_CODE": 141, ISO2: "LB", name: "Lebanon" },
    { "ADM0_CODE": 142, ISO2: "LS", name: "Lesotho" },
    { "ADM0_CODE": 144, ISO2: "LR", name: "Liberia" },
    { "ADM0_CODE": 145, ISO2: "LY", name: "Libya" },
    { "ADM0_CODE": 146, ISO2: "LI", name: "Liechtenstein" },
    { "ADM0_CODE": 147, ISO2: "LT", name: "Lithuania" },
    { "ADM0_CODE": 148, ISO2: "LU", name: "Luxembourg" },
    { "ADM0_CODE": 149, ISO2: "MO", name: "Macao" },
    { "ADM0_CODE": 150, ISO2: "MG", name: "Madagascar" },
    { "ADM0_CODE": 152, ISO2: "MW", name: "Malawi" },
    { "ADM0_CODE": 153, ISO2: "MY", name: "Malaysia" },
    { "ADM0_CODE": 154, ISO2: "MV", name: "Maldives" },
    { "ADM0_CODE": 155, ISO2: "ML", name: "Mali" },
    { "ADM0_CODE": 156, ISO2: "MT", name: "Malta" },
    { "ADM0_CODE": 157, ISO2: "MH", name: "Marshall Islands" },
    { "ADM0_CODE": 158, ISO2: "MQ", name: "Martinique" },
    { "ADM0_CODE": 159, ISO2: "MR", name: "Mauritania" },
    { "ADM0_CODE": 160, ISO2: "MU", name: "Mauritius" },
    { "ADM0_CODE": 161, ISO2: "YT", name: "Mayotte" },
    { "ADM0_CODE": 162, ISO2: "MX", name: "Mexico" },
    { "ADM0_CODE": 163, ISO2: "FM", name: "Micronesia (Federated States of)" },
    { "ADM0_CODE": 165, ISO2: "MD", name: "Moldova, Republic of" },
    { "ADM0_CODE": 166, ISO2: "MC", name: "Monaco" },
    { "ADM0_CODE": 167, ISO2: "MN", name: "Mongolia" },
    { "ADM0_CODE": 2647, ISO2: "ME", name: "Montenegro" },
    { "ADM0_CODE": 168, ISO2: "MS", name: "Montserrat" },
    { "ADM0_CODE": 169, ISO2: "MA", name: "Morocco" },
    { "ADM0_CODE": 170, ISO2: "MZ", name: "Mozambique" },
    { "ADM0_CODE": 171, ISO2: "MM", name: "Myanmar" },
    { "ADM0_CODE": 172, ISO2: "NA", name: "Namibia" },
    { "ADM0_CODE": 173, ISO2: "NR", name: "Nauru" },
    { "ADM0_CODE": 175, ISO2: "NP", name: "Nepal" },
    { "ADM0_CODE": 177, ISO2: "NL", name: "Netherlands, Kingdom of the" },
    // { "ADM0_CODE": 176, ISO2: "AN", name: "#N/A" },
    { "ADM0_CODE": 178, ISO2: "NC", name: "New Caledonia" },
    { "ADM0_CODE": 179, ISO2: "NZ", name: "New Zealand" },
    { "ADM0_CODE": 180, ISO2: "NI", name: "Nicaragua" },
    { "ADM0_CODE": 181, ISO2: "NE", name: "Niger" },
    { "ADM0_CODE": 182, ISO2: "NG", name: "Nigeria" },
    { "ADM0_CODE": 183, ISO2: "NU", name: "Niue" },
    { "ADM0_CODE": 184, ISO2: "NF", name: "Norfolk Island" },
    { "ADM0_CODE": 185, ISO2: "MP", name: "Northern Mariana Islands" },
    { "ADM0_CODE": 186, ISO2: "NO", name: "Norway" },
    { "ADM0_CODE": 187, ISO2: "OM", name: "Oman" },
    { "ADM0_CODE": 188, ISO2: "PK", name: "Pakistan" },
    { "ADM0_CODE": 189, ISO2: "PW", name: "Palau" },
    { "ADM0_CODE": 191, ISO2: "PA", name: "Panama" },
    { "ADM0_CODE": 192, ISO2: "PG", name: "Papua New Guinea" },
    { "ADM0_CODE": 194, ISO2: "PY", name: "Paraguay" },
    { "ADM0_CODE": 195, ISO2: "PE", name: "Peru" },
    { "ADM0_CODE": 196, ISO2: "PH", name: "Philippines" },
    { "ADM0_CODE": 197, ISO2: "PN", name: "Pitcairn" },
    { "ADM0_CODE": 198, ISO2: "PL", name: "Poland" },
    { "ADM0_CODE": 199, ISO2: "PT", name: "Portugal" },
    { "ADM0_CODE": 200, ISO2: "PR", name: "Puerto Rico" },
    { "ADM0_CODE": 201, ISO2: "QA", name: "Qatar" },
    { "ADM0_CODE": 202, ISO2: "KR", name: "Korea, Republic of" },
    { "ADM0_CODE": 206, ISO2: "RE", name: "Réunion" },
    { "ADM0_CODE": 203, ISO2: "RO", name: "Romania" },
    { "ADM0_CODE": 204, ISO2: "RU", name: "Russian Federation" },
    { "ADM0_CODE": 205, ISO2: "RW", name: "Rwanda" },
    { "ADM0_CODE": 207, ISO2: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
    { "ADM0_CODE": 208, ISO2: "KN", name: "Saint Kitts and Nevis" },
    { "ADM0_CODE": 209, ISO2: "LC", name: "Saint Lucia" },
    { "ADM0_CODE": 210, ISO2: "PM", name: "Saint Pierre and Miquelon" },
    { "ADM0_CODE": 211, ISO2: "VC", name: "Saint Vincent and the Grenadines" },
    { "ADM0_CODE": 212, ISO2: "WS", name: "Samoa" },
    { "ADM0_CODE": 213, ISO2: "SM", name: "San Marino" },
    { "ADM0_CODE": 214, ISO2: "ST", name: "Sao Tome and Principe" },
    { "ADM0_CODE": 215, ISO2: "SA", name: "Saudi Arabia" },
    { "ADM0_CODE": 217, ISO2: "SN", name: "Senegal" },
    { "ADM0_CODE": 2648, ISO2: "RS", name: "Serbia" },
    { "ADM0_CODE": 220, ISO2: "SC", name: "Seychelles" },
    { "ADM0_CODE": 221, ISO2: "SL", name: "Sierra Leone" },
    { "ADM0_CODE": 222, ISO2: "SG", name: "Singapore" },
    { "ADM0_CODE": 223, ISO2: "SK", name: "Slovakia" },
    { "ADM0_CODE": 224, ISO2: "SI", name: "Slovenia" },
    { "ADM0_CODE": 225, ISO2: "SB", name: "Solomon Islands" },
    { "ADM0_CODE": 226, ISO2: "SO", name: "Somalia" },
    { "ADM0_CODE": 227, ISO2: "ZA", name: "South Africa" },
    { "ADM0_CODE": 228, ISO2: "GS", name: "South Georgia and the South Sandwich Islands" },
    { "ADM0_CODE": 74, ISO2: "SS", name: "South Sudan" },
    { "ADM0_CODE": 229, ISO2: "ES", name: "Spain" },
    { "ADM0_CODE": 231, ISO2: "LK", name: "Sri Lanka" },
    { "ADM0_CODE": 6, ISO2: "SD", name: "Sudan" },
    { "ADM0_CODE": 233, ISO2: "SR", name: "Suriname" },
    { "ADM0_CODE": 234, ISO2: "SJ", name: "Svalbard and Jan Mayen" },
    { "ADM0_CODE": 235, ISO2: "SZ", name: "Eswatini" },
    { "ADM0_CODE": 236, ISO2: "SE", name: "Sweden" },
    { "ADM0_CODE": 237, ISO2: "CH", name: "Switzerland" },
    { "ADM0_CODE": 238, ISO2: "SY", name: "Syrian Arab Republic" },
    { "ADM0_CODE": 147296, ISO2: "TW", name: "Taiwan, Province of China" },
    { "ADM0_CODE": 239, ISO2: "TJ", name: "Tajikistan" },
    { "ADM0_CODE": 240, ISO2: "TH", name: "Thailand" },
    { "ADM0_CODE": 241, ISO2: "MK", name: "North Macedonia" },
    { "ADM0_CODE": 242, ISO2: "TL", name: "Timor-Leste" },
    { "ADM0_CODE": 243, ISO2: "TG", name: "Togo" },
    { "ADM0_CODE": 244, ISO2: "TK", name: "Tokelau" },
    { "ADM0_CODE": 245, ISO2: "TO", name: "Tonga" },
    { "ADM0_CODE": 246, ISO2: "TT", name: "Trinidad and Tobago" },
    { "ADM0_CODE": 248, ISO2: "TN", name: "Tunisia" },
    { "ADM0_CODE": 249, ISO2: "TR", name: "Türkiye" },
    { "ADM0_CODE": 250, ISO2: "TM", name: "Turkmenistan" },
    { "ADM0_CODE": 251, ISO2: "TC", name: "Turks and Caicos Islands" },
    { "ADM0_CODE": 252, ISO2: "TV", name: "Tuvalu" },
    { "ADM0_CODE": 256, ISO2: "GB", name: "United Kingdom of Great Britain and Northern Ireland" },
    { "ADM0_CODE": 253, ISO2: "UG", name: "Uganda" },
    { "ADM0_CODE": 254, ISO2: "UA", name: "Ukraine" },
    { "ADM0_CODE": 255, ISO2: "AE", name: "United Arab Emirates" },
    { "ADM0_CODE": 257, ISO2: "TZ", name: "Tanzania, United Republic of" },
    { "ADM0_CODE": 259, ISO2: "US", name: "United States of America" },
    { "ADM0_CODE": 258, ISO2: "VI", name: "Virgin Islands (U.S.)" },
    { "ADM0_CODE": 260, ISO2: "UY", name: "Uruguay" },
    { "ADM0_CODE": 261, ISO2: "UZ", name: "Uzbekistan" },
    { "ADM0_CODE": 262, ISO2: "VU", name: "Vanuatu" },
    { "ADM0_CODE": 263, ISO2: "VE", name: "Venezuela (Bolivarian Republic of)" },
    { "ADM0_CODE": 264, ISO2: "VN", name: "Viet Nam" },
    // { "ADM0_CODE": 265, ISO2: "WK", name: "#N/A" },
    { "ADM0_CODE": 266, ISO2: "WF", name: "Wallis and Futuna" },
    // 267	 	West Bank	#N / A
    { "ADM0_CODE": 268, ISO2: "EH", name: "Western Sahara" },
    { "ADM0_CODE": 269, ISO2: "YE", name: "Yemen" },
    { "ADM0_CODE": 270, ISO2: "ZM", name: "Zambia" },
    { "ADM0_CODE": 271, ISO2: "ZW", name: "Zimbabwe" },
]

exports.gaul2iso = function(gaul) {
    const country = codes.find(c => c.ADM0_CODE === gaul)
    return country?.ISO2 || null;
}

exports.getIso2CountryName = function(iso2) {
    const country = codes.find(c => c.ISO2 === iso2)
    return country?.name || null;
}
