image: node:latest
definitions:
  steps:
    - step: &build
        name: Build_Firebase
        image: adoptopenjdk/openjdk16:jdk-16.0.1_9-slim
        script:
          - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
          - bash nodesource_setup.sh
          - apt install nodejs
          - npm install --global yarn
          - npm install
          - npm run build
        artifacts:
          - public/**

    - step: &deploy
        name: Deploy_Firebase
        script:
          - cd functions; npm install; cd ..
          - pipe: atlassian/firebase-deploy:1.2.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN 
              PROJECT_ID: $PROJECT_ID
              DEBUG: 'true'

    - step: &deploy-functions
        name: Deploy_Functions
        image: google/cloud-sdk:latest
        script:
          - export REGION=europe-west3
          - export BUCKET="gs://fao-ferm-functions-staging"
          - echo $PROJECT_KEYFILE > gcloud-api-key.json
          - export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/gcloud-api-key.json"
          - gcloud auth activate-service-account --key-file "${GOOGLE_APPLICATION_CREDENTIALS}"
          - gcloud functions deploy get_zonal_stats --region=$REGION --source=./cloud-functions/functions/get_area --runtime=python39 --stage-bucket=$BUCKET #--trigger-http --allow-unauthenticated
pipelines:
  branches:
    review:
      - step: *build
      - step:
          <<: *deploy
          deployment: review 
    master:
      - step:
          <<: *deploy-functions
          deployment: prod-gcf
      - step: *build
      - step:
          <<: *deploy
          deployment: prod

