image: node:latest
definitions:
  steps:
    - step: &build
        name: Build_Firebase
        image: adoptopenjdk/openjdk16:jdk-16.0.1_9-slim
        script:
          - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
          - bash nodesource_setup.sh
          - apt install nodejs
          - npm install
          - npm run build
        artifacts:
          - public/**

    - step: &deploy
        name: Deploy_Firebase
        script:
          - pipe: atlassian/firebase-deploy:0.2.1
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN 
              PROJECT_ID: $PROJECT_ID
pipelines:
  branches:
    review:
      - step: *build
      - step:
          <<: *deploy
          deployment: review 
    master:
      - step: *build
      - step:
          <<: *deploy
          deployment: prod
