(ns drip.menus)

(defonce status-items [[:accepted          "Accepted"]
                       [:completed         "Completed"]
                       [:deprecated        "Deprecated"]
                       [:final             "Final"]
                       [:historicalArchive "Historical archive"]
                       [:notAccepted       "Not Accepted"]
                       [:obsolete          "Obsolete"]
                       [:onGoing           "On going"]
                       [:pending           "Pending"]
                       [:planned           "Planned"]
                       [:proposed          "Proposed"]
                       [:required          "Required"]
                       [:retired           "Retired"]
                       [:superseded        "Superseded"]
                       [:tentative         "Tentative"]
                       [:underDevelopment  "Under development"]
                       [:valid             "Valid"]
                       [:withdrawn         "Withdrawn"]])

(defonce date-types [[:adopted         "Adopted"]
                     [:creation        "Creation"]
                     [:deprecated      "Deprecated"]
                     [:distribution    "Distribution"]
                     [:expiry          "Expiry"]
                     [:inForce         "In Force"]
                     [:lastRevision    "Last Revision"]
                     [:lastUpdate      "Last Update"]
                     [:nextUpdate      "Next Update"]
                     [:publication     "Publication"]
                     [:released        "Released"]
                     [:revision        "Revision"]
                     [:superseded      "Superseded"]
                     [:unavailable     "Unavailable"]
                     [:validityBegins  "Validity Begins"]
                     [:validityExpires "Validity Expires"]])

(defonce poc-roles [[:author               "Author"]
                   [:coAuthor              "Co-author"]
                   [:collaborator          "Collaborator"]
                   [:contributor           "Contributor"]
                   [:custodian             "Custodian"]
                   [:distributor           "Distributor"]
                   [:editor                "Editor"]
                   [:funder                "Funder"]
                   [:mediator              "Mediator"]
                   [:originator            "Originator"]
                   [:owner                 "Owner"]
                   [:pointOfContact        "Point of contact"]
                   [:principalInvestigator "Principal investigator"]
                   [:processor             "Processor"]
                   [:publisher             "Publisher"]
                   [:resourceProvider      "Resource provider"]
                   [:rightsHolder          "Rights holder"]
                   [:sponsor               "Sponsor"]
                   [:stakeholder           "Stakeholder"]
                   [:user                  "User"]])

(defonce keyword-types [[:dataCentre "Data centre"]
                        [:discipline "Discipline"]
                        [:featureType "Feature type"]
                        [:instrument "Instrument"]
                        [:place "Place"]
                        [:platform "Platform"]
                        [:process "Process"]
                        [:product "Product"]
                        [:project "Project"]
                        [:service "Service"]
                        [:stratum "Stratum"]
                        [:subTopicCategory "Sub-Topic Category"]
                        [:taxon "Taxon"]
                        [:temporal "Temporal"]
                        [:theme "Theme"]])

(defonce keywords [["Farming"]
                   ["Boundaries"]
                   ["Climatology, meteorology, atmosphere"]
                   ["Economy"]
                   ["Elevation"]
                   ["Health"]
                   ["Imagery base maps earth cover"]
                   ["Intelligence military"]
                   ["Inland waters"]
                   ["Location"]
                   ["Oceans"]
                   ["Planning cadastre"]
                   ["Society"]
                   ["Structure"]
                   ["Transportation"]
                   ["Utilities communication"]
                   ["Extra Terrestrial"]
                   ["Disaster"]])




(defonce reporting-processes [[:ferm "FERM"]
                              [:drip "DRIP"]])

(defonce agencies [[:fao "FAO"]
                   [:ifad "IFAD"]
                   [:wfp "WFP"]])

(defonce project-statuses
  [[1 "Pipeline/identification"]
   [2 "Implementation"]
   [3 "Finalisation"]
   [4 "Closed"]
   [5 "Cancelled"]
   [6 "Suspended"]])

(defonce funding-sources
  [[:1 "GNI: Gross National Income"]
   [:110 "Standard grant"]
   [:1100 "Guarantees/insurance"]
   [:111 "Subsidies to national private investors"]
   [:2 "ODA % GNI"]
   [:210 "Interest subsidy"]
   [:211 "Interest subsidy to national private exporters"]
   [:3 "Total Flows % GNI"]
   [:310 "Capital subscription on deposit basis"]
   [:311 "Capital subscription on encashment basis"]
   [:4 "Population"]
   [:410 "Aid loan excluding debt reorganisation"]
   [:411 "Investment-related loan to developing countries"]
   [:412 "Loan in a joint venture with the recipient"]
   [:413 "Loan to national private investor"]
   [:414 "Loan to national private exporter"]
   [:421 "Standard loan"]
   [:422 "Reimbursable grant"]
   [:423 "Bonds"]
   [:424 "Asset-backed securities"]
   [:425 "Other debt securities"]
   [:431 "Subordinated loan"]
   [:432 "Preferred equity"]
   [:433 "Other hybrid instruments"]
   [:451 "Non-banks guaranteed export credits"]
   [:452 "Non-banks non-guaranteed portions of guaranteed export credits"]
   [:453 "Bank export credits"]
   [:510 "Common equity"]
   [:511 "Acquisition of equity not part of joint venture in developing countries"]
   [:512 "Other acquisition of equity"]
   [:520 "Shares in collective investment vehicles"]
   [:530 "Reinvested earnings"]
   [:610 "Debt forgiveness:  ODA claims (P)"]
   [:611 "Debt forgiveness: ODA claims (I)"]
   [:612 "Debt forgiveness: OOF claims (P)"]
   [:613 "Debt forgiveness: OOF claims (I)"]
   [:614 "Debt forgiveness:  Private claims (P)"]
   [:615 "Debt forgiveness:  Private claims (I)"]
   [:616 "Debt forgiveness: OOF claims (DSR)"]
   [:617 "Debt forgiveness:  Private claims (DSR)"]
   [:618 "Debt forgiveness: Other"]
   [:620 "Debt rescheduling: ODA claims (P)"]
   [:621 "Debt rescheduling: ODA claims (I)"]
   [:622 "Debt rescheduling: OOF claims (P)"]
   [:623 "Debt rescheduling: OOF claims (I)"]
   [:624 "Debt rescheduling:  Private claims (P)"]
   [:625 "Debt rescheduling:  Private claims (I)"]
   [:626 "Debt rescheduling: OOF claims (DSR)"]
   [:627 "Debt rescheduling:  Private claims (DSR)"]
   [:630 "Debt rescheduling: OOF claim (DSR \u2013 original loan principal)"]
   [:631 "Debt rescheduling: OOF claim (DSR \u2013 original loan interest)"]
   [:632 "Debt rescheduling: Private claim (DSR \u2013 original loan principal)"]
   [:633 "Debt forgiveness/conversion: export credit claims (P)"]
   [:634 "Debt forgiveness/conversion:  export credit claims (I)"]
   [:635 "Debt forgiveness:  export credit claims (DSR)"]
   [:636 "Debt rescheduling:  export credit claims (P)"]
   [:637 "Debt rescheduling:  export credit claims (I)"]
   [:638 "Debt rescheduling:  export credit claims (DSR)"]
   [:639 "Debt rescheduling:  export credit claim (DSR \u2013 original loan principal)"]
   [:710 "Foreign direct investment, new capital outflow (includes reinvested earnings if separate identification not available)"]
   [:711 "Other foreign direct investment, including reinvested earnings"]
   [:712 "Foreign direct investment, reinvested earnings"]
   [:810 "Bank bonds"]
   [:811 "Non-bank  bonds"]
   [:910 "Other bank securities/claims"]
   [:911 "Other non-bank securities/claims"]
   [:912 "Purchase of securities from issuing agencies"]
   [:913 "Securities and other instruments originally issued by multilateral agencies"]])

(defonce countries
  [["AF" "Afghanistan"]
   ["AX" "\u00c5land Islands"]
   ["AL" "Albania"]
   ["DZ" "Algeria"]
   ["AS" "American Samoa"]
   ["AD" "Andorra"]
   ["AO" "Angola"]
   ["AI" "Anguilla"]
   ["AQ" "Antarctica"]
   ["AG" "Antigua and Barbuda"]
   ["AR" "Argentina"]
   ["AM" "Armenia"]
   ["AW" "Aruba"]
   ["AU" "Australia"]
   ["AT" "Austria"]
   ["AZ" "Azerbaijan"]
   ["BS" "Bahamas (the)"]
   ["BH" "Bahrain"]
   ["BD" "Bangladesh"]
   ["BB" "Barbados"]
   ["BY" "Belarus"]
   ["BE" "Belgium"]
   ["BZ" "Belize"]
   ["BJ" "Benin"]
   ["BM" "Bermuda"]
   ["BT" "Bhutan"]
   ["BO" "Bolivia (Plurinational State of)"]
   ["BQ" "Bonaire, Sint Eustatius and Saba"]
   ["BA" "Bosnia and Herzegovina"]
   ["BW" "Botswana"]
   ["BV" "Bouvet Island"]
   ["BR" "Brazil"]
   ["IO" "British Indian Ocean Territory (the)"]
   ["BN" "Brunei Darussalam"]
   ["BG" "Bulgaria"]
   ["BF" "Burkina Faso"]
   ["BI" "Burundi"]
   ["KH" "Cambodia"]
   ["CM" "Cameroon"]
   ["CA" "Canada"]
   ["CV" "Cabo Verde"]
   ["KY" "Cayman Islands (the)"]
   ["CF" "Central African Republic (the)"]
   ["TD" "Chad"]
   ["CL" "Chile"]
   ["CN" "China"]
   ["CX" "Christmas Island"]
   ["CC" "Cocos (Keeling) Islands (the)"]
   ["CO" "Colombia"]
   ["KM" "Comoros (the)"]
   ["CG" "Congo (the)"]
   ["CD" "Congo (the Democratic Republic of the)"]
   ["CK" "Cook Islands (the)"]
   ["CR" "Costa Rica"]
   ["CI" "C\u00f4te d'Ivoire"]
   ["HR" "Croatia"]
   ["CU" "Cuba"]
   ["CW" "Cura\u00e7ao"]
   ["CY" "Cyprus"]
   ["CZ" "Czechia"]
   ["DK" "Denmark"]
   ["DJ" "Djibouti"]
   ["DM" "Dominica"]
   ["DO" "Dominican Republic (the)"]
   ["EC" "Ecuador"]
   ["EG" "Egypt"]
   ["SV" "El Salvador"]
   ["GQ" "Equatorial Guinea"]
   ["ER" "Eritrea"]
   ["EE" "Estonia"]
   ["ET" "Ethiopia"]
   ["FK" "Falkland Islands (the) [Malvinas]"]
   ["FO" "Faroe Islands (the)"]
   ["FJ" "Fiji"]
   ["FI" "Finland"]
   ["FR" "France"]
   ["GF" "French Guiana"]
   ["PF" "French Polynesia"]
   ["TF" "French Southern Territories (the)"]
   ["GA" "Gabon"]
   ["GM" "Gambia (the)"]
   ["GE" "Georgia"]
   ["DE" "Germany"]
   ["GH" "Ghana"]
   ["GI" "Gibraltar"]
   ["GR" "Greece"]
   ["GL" "Greenland"]
   ["GD" "Grenada"]
   ["GP" "Guadeloupe"]
   ["GU" "Guam"]
   ["GT" "Guatemala"]
   ["GG" "Guernsey"]
   ["GN" "Guinea"]
   ["GW" "Guinea-Bissau"]
   ["GY" "Guyana"]
   ["HT" "Haiti"]
   ["HM" "Heard Island and McDonald Islands"]
   ["VA" "Holy See (the)"]
   ["HN" "Honduras"]
   ["HK" "Hong Kong"]
   ["HU" "Hungary"]
   ["IS" "Iceland"]
   ["IN" "India"]
   ["code" "Indonesia"]
   ["IR" "Iran (Islamic Republic of)"]
   ["IQ" "Iraq"]
   ["IE" "Ireland"]
   ["IM" "Isle of Man"]
   ["IL" "Israel"]
   ["IT" "Italy"]
   ["JM" "Jamaica"]
   ["JP" "Japan"]
   ["JE" "Jersey"]
   ["JO" "Jordan"]
   ["KZ" "Kazakhstan"]
   ["KE" "Kenya"]
   ["KI" "Kiribati"]
   ["KP" "Korea (the Democratic People's Republic of)"]
   ["KR" "Korea (the Republic of)"]
   ["XK" "Kosovo"]
   ["KW" "Kuwait"]
   ["KG" "Kyrgyzstan"]
   ["LA" "Lao People's Democratic Republic (the)"]
   ["LV" "Latvia"]
   ["LB" "Lebanon"]
   ["LS" "Lesotho"]
   ["LR" "Liberia"]
   ["LY" "Libya"]
   ["LI" "Liechtenstein"]
   ["LT" "Lithuania"]
   ["LU" "Luxembourg"]
   ["MO" "Macao"]
   ["MK" "North Macedonia"]
   ["MG" "Madagascar"]
   ["MW" "Malawi"]
   ["MY" "Malaysia"]
   ["MV" "Maldives"]
   ["ML" "Mali"]
   ["MT" "Malta"]
   ["MH" "Marshall Islands (the)"]
   ["MQ" "Martinique"]
   ["MR" "Mauritania"]
   ["MU" "Mauritius"]
   ["YT" "Mayotte"]
   ["MX" "Mexico"]
   ["FM" "Micronesia (Federated States of)"]
   ["MD" "Moldova (the Republic of)"]
   ["MC" "Monaco"]
   ["MN" "Mongolia"]
   ["ME" "Montenegro"]
   ["MS" "Montserrat"]
   ["MA" "Morocco"]
   ["MZ" "Mozambique"]
   ["MM" "Myanmar"]
   ["NA" "Namibia"]
   ["NR" "Nauru"]
   ["NP" "Nepal"]
   ["NL" "Netherlands (the)"]
   ["AN" "NETHERLAND ANTILLES"]
   ["NC" "New Caledonia"]
   ["NZ" "New Zealand"]
   ["NI" "Nicaragua"]
   ["NE" "Niger (the)"]
   ["NG" "Nigeria"]
   ["NU" "Niue"]
   ["NF" "Norfolk Island"]
   ["MP" "Northern Mariana Islands (the)"]
   ["NO" "Norway"]
   ["OM" "Oman"]
   ["PK" "Pakistan"]
   ["PW" "Palau"]
   ["PS" "Palestine, State of"]
   ["PA" "Panama"]
   ["PG" "Papua New Guinea"]
   ["PY" "Paraguay"]
   ["PE" "Peru"]
   ["PH" "Philippines (the)"]
   ["PN" "Pitcairn"]
   ["PL" "Poland"]
   ["PT" "Portugal"]
   ["PR" "Puerto Rico"]
   ["QA" "Qatar"]
   ["RE" "R\u00e9union"]
   ["RO" "Romania"]
   ["RU" "Russian Federation (the)"]
   ["RW" "Rwanda"]
   ["BL" "Saint Barth\u00e9lemy"]
   ["SH" "Saint Helena, Ascension and Tristan da Cunha"]
   ["KN" "Saint Kitts and Nevis"]
   ["LC" "Saint Lucia"]
   ["MF" "Saint Martin (French part)"]
   ["PM" "Saint Pierre and Miquelon"]
   ["VC" "Saint Vincent and the Grenadines"]
   ["WS" "Samoa"]
   ["SM" "San Marino"]
   ["ST" "Sao Tome and Principe"]
   ["SA" "Saudi Arabia"]
   ["SN" "Senegal"]
   ["RS" "Serbia"]
   ["SC" "Seychelles"]
   ["SL" "Sierra Leone"]
   ["SG" "Singapore"]
   ["SX" "Sint Maarten (Dutch part)"]
   ["SK" "Slovakia"]
   ["SI" "Slovenia"]
   ["SB" "Solomon Islands"]
   ["SO" "Somalia"]
   ["ZA" "South Africa"]
   ["GS" "South Georgia and the South Sandwich Islands"]
   ["SS" "South Sudan"]
   ["ES" "Spain"]
   ["LK" "Sri Lanka"]
   ["SD" "Sudan (the)"]
   ["SR" "Suriname"]
   ["SJ" "Svalbard and Jan Mayen"]
   ["SZ" "Eswatini"]
   ["SE" "Sweden"]
   ["CH" "Switzerland"]
   ["SY" "Syrian Arab Republic"]
   ["TW" "Taiwan (Province of China)"]
   ["TJ" "Tajikistan"]
   ["TZ" "Tanzania, United Republic of"]
   ["TH" "Thailand"]
   ["TL" "Timor-Leste"]
   ["TG" "Togo"]
   ["TK" "Tokelau"]
   ["TO" "Tonga"]
   ["TT" "Trinidad and Tobago"]
   ["TN" "Tunisia"]
   ["TR" "Turkey"]
   ["TM" "Turkmenistan"]
   ["TC" "Turks and Caicos Islands (the)"]
   ["TV" "Tuvalu"]
   ["UG" "Uganda"]
   ["UA" "Ukraine"]
   ["AE" "United Arab Emirates (the)"]
   ["GB" "United Kingdom of Great Britain and Northern Ireland (the)"]
   ["US" "United States of America (the)"]
   ["UM" "United States Minor Outlying Islands (the)"]
   ["UY" "Uruguay"]
   ["UZ" "Uzbekistan"]
   ["VU" "Vanuatu"]
   ["VE" "Venezuela (Bolivarian Republic of)"]
   ["VN" "Viet Nam"]
   ["VG" "Virgin Islands (British)"]
   ["VI" "Virgin Islands (U.S.)"]
   ["WF" "Wallis and Futuna"]
   ["EH" "Western Sahara"]
   ["YE" "Yemen"]
   ["ZM" "Zambia"]
   ["ZW" "Zimbabwe"]])

(defonce sdg-contributions
  [[:1 "Goal 1. End poverty in all its forms everywhere"]
  [:2 "Goal 2. End hunger, achieve food security and improved nutrition and promote sustainable agriculture"]
  [:3 "Goal 3. Ensure healthy lives and promote well-being for all at all ages"]
  [:4 "Goal 4. Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all"]
  [:5 "Goal 5. Achieve gender equality and empower all women and girls"]
  [:6 "Goal 6. Ensure availability and sustainable management of water and sanitation for all"]
  [:7 "Goal 7. Ensure access to affordable, reliable, sustainable and modern energy for all"]
  [:8 "Goal 8. Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all"]
  [:9 "Goal 9. Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation"]
  [:10 "Goal 10. Reduce inequality within and among countries"]
  [:11 "Goal 11. Make cities and human settlements inclusive, safe, resilient and sustainable"]
  [:12 "Goal 12. Ensure sustainable consumption and production patterns"]
  [:13 "Goal 13. Take urgent action to combat climate change and its impacts"]
  [:14 "Goal 14. Conserve and sustainably use the oceans, seas and marine resources for sustainable development"]
  [:15 "Goal 15. Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss"]
  [:16 "Goal 16. Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels"]
  [:17 "Goal 17. Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development"]])

(defonce natural-disasters
  [[:1 "Biological"]
   [:2 "Epidemic"]
   [:3 "Insect infestation"]
   [:4 "Animal Stampede"]
   [:5 "Geophysical"]
   [:6 "Earthquake"]
   [:7 "Volcano"]
   [:8 "Mass movement dry (rockfall, landslides, avalanche)"]
   [:9 "Hydrological"]
   [:10 "Flood"]
   [:11 "Mass movement wet (rockfall, landslides, avalanche)"]
   [:12 "Meteorological"]
   [:13 "Storm"]
   [:14 "Climatological"]
   [:15 "Extreme temperature"]
   [:16 "Drought"]
   [:17 "Wildfire"]])

(defonce ecosystem-degradation-types
  [[:1 "soil erosion by water "]
   [:2 "soil erosion by wind "]
   [:3 "chemical soil deterioration "]
   [:4 "physical soil deterioration "]
   [:5 "biological degradation "]
   [:6 "water degradation "]
   [:7 "other"]])

(defonce ecosystem-degradation-degree
  [[:1 "Light"]
   [:2 "Moderate"]
   [:3 "Strong"]
   [:4 "Extreme"]])

(defonce land-degradation-drivers
  [[:1 "Grazing land management"]
   [:2 "Croplands and agroforestry management"]
   [:3 "forests and tree plantation management"]
   [:4 "non-timber natural resource extraction"]
   [:5 "fire regime changes"]
   [:6 "introduction of invasive species"]
   [:7 "extractive industry development"]
   [:8 "infrastructure and industrial development and urbanization"]
   [:9 "DEMOGRAPHIC"]
   [:10 "economic"]
   [:11 "science, knowledge and technology"]
   [:12 "insitutions and governance"]
   [:13 "cultural"]
   [:14 "drainage (wetlands)"]
   [:15 "alteration of vegetation"]])

(defonce bool
  [[:1 "Yes"]
   [:0 "No"]])

(defonce land-use
  [[:1 "Subsistence agriculture"]
   [:2 "Intensive agriculture"]
   [:3 "Grazing"]
   [:4 "Collection of non-wood forest products"]
   [:5 "Fuelwood, Timber"]
   [:6 "Mining"]
   [:7 "Waste disposal"]
   [:8 "Settlements, urban area, infrastructures"]
   [:9 "Nature conservation"]
   [:10 "Recreation"]
   [:11 "Spiritual (i.e. sacred forests"]
   [:12 "Other"]])

(defonce land-tenure
  [[:1 "Ownership private individual"]
   [:2 "Ownership private communal"]
   [:3 "Ownership public"]
   [:4 "Ownership titled"]
   [:5 "Ownership untitled"]
   [:6 "Use individual"]
   [:7 "Use communal"]
   [:8 "Use titled"]
   [:9 "Use untitled"]])

(defonce stakeholder-engagement
  [[:1 "Design and Planning"]
   [:2 "Coordination"]
   [:3 "Capacity development"]
   [:4 "Technical supervision"]
   [:5 "Plant production"]
   [:6 "Site selection"]
   [:7 "Planting"]
   [:8 "Plant maintenance"]
   [:9 "Site surveillance"]
   [:10 "Monitoring of LDN indicators"]
   [:11 "Monitoring of project success"]
   [:12 "Communication"]])

(defonce gender-mainstreaming-activities
  [[:1 "Yes"]
   [:2 "No"]
   [:3 "Planned"]])

;; TODO: implement as multi-level menu once multi-level menus are implemented
(defonce activities
  [[:1 "Restore/improve forest land - Reduce/halt deforestation and conversion of forest to other land cover types (includes conserving forest land) "]
   [:2 "Restore/improve forest land - Restore forest land "]
   [:3 "Restore/improve forest land - Increase land productivity in forest areas "]
   [:4 "Restore/improve forest land - Improve forest management e.g. fire management "]
   [:5 "Increase forest land - Increase forest land (net gain) e.g. plantations "]
   [:6 "Restore/improve cropland - Increase land productivity in agricultural areas "]
   [:7 "Restore/improve cropland - Rehabilitate bare or degraded land for crop production "]
   [:8 "Restore/improve cropland - Improve water use for irrigation "]
   [:9 "Restore/improve cropland - Halt/reduce conversion of cropland to other land cover types "]
   [:10 "Restore/improve cropland - Sustainable Land Management "]
   [:11 "Restore/improve grassland and savannah - Restore and improve pastures "]
   [:12 "Restore/improve grassland and savannah - Improve land productivity in grassland/savannah "]
   [:13 "Restore/improve grassland and savannah - Restore rangeland (e.g. by controlling livestock and wildfires) "]
   [:14 "Restore/improve grassland and savannah - Halt/reduce conversion of grassland to other land cover types "]
   [:15 "Restore/improve wetlands (including peatlands and mangroves) - Halt/reduce wetland conversion to other land uses (includes conserving wetlands) "]
   [:16 "Restore/improve wetlands (including peatlands and mangroves) - Restore/preserve wetlands and reduce degradation of wetlands "]
   [:17 "Increase soil fertility and carbon stock - Rehabilitate bare land and/or restore degraded land "]
   [:18 "Increase soil fertility and carbon stock - Increase carbon stock and reduce soil/land degradation "]
   [:19 "Increase soil fertility and carbon stock - Maintain current level of SOC "]
   [:20 "Increase soil fertility and carbon stock - Reduce soil erosion "]
   [:21 "Increase soil fertility and carbon stock - Reduce sand encroachment "]
   [:22 "Increase soil fertility and carbon stock - Improve watershed/landscape management "]
   [:23 "Manage artificial area and mining - Restore degraded mining areas "]
   [:24 "Manage artificial area and mining - Halt illegal mining and/or reduce mining area "]
   [:25 "Manage artificial area and mining - Improve land productivity in artificial areas "]
   [:26 "Manage artificial area and mining - Halt/reduce/regulate expansion of urban/artificial area "]
   [:27 "Restore /improve protected areas - Restore protected areas "]
   [:28 "Restore /improve protected areas - Improve management of protected areas "]
   [:29 "Increase protected areas - Increase protected areas "]
   [:30 "Improve coastal management - Reduce coastal erosion "]
   [:31 "Improve coastal management - Reduce saline water intrusion in coastal zone "]
   [:32 "Other/General/Unspecified - Avoid/Prevent/ halt degradation (of degraded lands) "]
   [:33 "Other/General/Unspecified - Restore vegetation cover (unspecified land use) "]
   [:34 "Other/General/Unspecified - Achieve LDN "]
   [:35 "Other/General/Unspecified - Improve land productivity (unspecified land use) "]
   [:36 "Other/General/Unspecified - Other/General/Unspecified "]
   [:37 "Instrument - General instrument (e.g. policies, economic incentives) "]
   [:38 "Restore/improve multiple land use - Forest and grassland "]
   [:39 "Restore/improve multiple land use - Cropland and grassland "]
   [:40 "Restore/improve multiple land use - Forest and wetlands "]
   [:41 "Restore/improve multiple land use - Forest, cropland and grassland "]
   [:42 "Restore/improve multiple land use - Protected area and forest "]
   [:43 "Restore/improve multiple land use - Other "]
   [:44 "Restore/improve multiple land use - All land uses "]
   [:45 "Reduce/halt conversion of multiple land uses - As above "]
   [:46 "Restore/improve multiple functions - Productivity and carbon stock "]
   [:47 "Restore/improve multiple functions - Other "]
   [:48 "Restore/improve multiple functions - Multiple functions "]
   [:49 "Restore/improve multiple functions in multiple land uses - Improve productivity and SOC stock in croplands and grasslands "]
   [:50 "Restore/improve multiple functions in multiple land uses - Other "]])

(defonce achieved
  [[:1 "Yes"]
   [:3 "Partially"]
   [:2 "No"]])

(defonce partially-achieved-reasons
  [[:3 "Lack of local buy-in"]
   [:4 "Drivers not fully addressed"]
   [:5 "Needs of stakeholder not fully taken into account"]
   [:6 "Natural disasters"]
   [:7 "Seedling failure"]
   [:8 "Seedling not adapted to site"]
   [:9 "Lack of law enforcement"]
   [:10 "Land tenure issues"]
   [:11 "Issues: technical implementation"]
   [:12 "Others"]])

(defonce technologies
  [{:code :A
    :name "Agronomic measures"
    :children [{:code :A1
                :name "Vegetation/ soil cover "}
               {:code :A2
                :name "Organic matter/ soil fertility"}
               {:code :A3
                :name "Soil surface treatment"}
               {:code :A4
                :name "Subsurface treatment"}
               {:code :A5
                :name "Seed management, improved varieties"}
               {:code :A6
                :name "Residue management"}
               {:code :A7
                :name "Others"}]}
   {:code :V
    :name "Vegetative measures"
    :children [{:code :V1
                :name "Tree and shrub cover"}
               {:code :V2
                :name "Grasses and perennial herbaceous plants"}
               {:code :V3
                :name "Clearing of vegetation Fire breaks, reduced fuel for forest fires"}
               {:code :V4
                :name "Replacement or removal of alien/invasive species"}
               {:code :V5
                :name "Others"}]}
   {:code :S
    :name "Structural measures"
    :children [{:code :S1
                :name "Terraces"}
               {:code :S2
                :name "Bunds, banks"}
               {:code :S3
                :name "Graded ditches, channels, waterways"}
               {:code :S4
                :name "Level ditches, pits"}
               {:code :S5
                :name "Dams, pans, ponds"}
               {:code :S6
                :name "Walls, barriers, palisades, fences"}
               {:code :S7
                :name "Water harvesting/ supply/ irrigation equipment"}
               {:code :S8
                :name "Sanitation/ waste water structures"}
               {:code :S9
                :name "Shelters for plants and animals"}
               {:code :S10
                :name " Energy saving measures"}]}
   {:code :M
    :name "Management measures"
    :children [{:code :M1
                :name "Change in land use type"}
               {:code :M2
                :name "Change in management/ intensity level"}
               {:code :M3
                :name "Layout according to natural and human environment"}
               {:code :M4
                :name "Major change in timing of activities"}
               {:code :M5
                :name "Control/ change in species composition  (if annually or in a rotational sequence as done e.g. on cropland A1)"}
               {:code :M6
                :name "Waste management (recycling, re-use or reduce)"}]}])